# Ejercicio 1> Agregar las variables de entorno necesarias para que la aplicacion "Flask" se conecte a MYSQL
#Se agregaron los valores a enviroment en db se pusieron los mismos para que coincidiera los de enviroment de app
# Ejercicio 2> Agregar php my admin a este docker-compose, y agregar nuevos varietales en la tabla wines del esquema drinks
#Se agrego en el compose los datos necesario para agregar phphmyadmin https://github.com/fuadajip/dockercompose-mysql-phpmyadmin/blob/master/docker-compose.yml
# Ejercicio 3> Persistir el contenido de la base de datos mysql en disco
#https://stackoverflow.com/questions/39175194/docker-compose-persistent-data-mysql
# Ejercicio 4> Hostear dos contenedores con la aplicación flask en puertos diferentes en el host (no hay que cambiar la aplicación)
# Ejercicio 5> Agregar al Dockerfile en ./app  la aplicación de linux "nano"

version: "2"

services:
  app:
    build: ./app
    links:
      - db
    ports:
      - 8830:5000 #8830 - localhost del host, 5000 del container
    environment:
      DB_USER_NAME: root
      DB_PASSWORD: root
      NAME_HELLO: Santi
  app2:
    build: ./app
    links:
      - db
    ports:
      - 8831:5000 #8831 - localhost del host, 5000 del container
    environment:
      DB_USER_NAME: root
      DB_PASSWORD: root
      NAME_HELLO: Santi numero 2


  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./../db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80